apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "veeamon-tour.fullname" . }}
  labels:
    app: {{ include "veeamon-tour.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "veeamon-tour.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "veeamon-tour.fullname" . }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: {{ include "veeamon-tour.mariadbHost" . }}
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: {{ .Values.mariadb.auth.database | quote }}
            - name: DB_USER
              value: {{ .Values.mariadb.auth.username | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "veeamon-tour.mariadbHost" . }}
                  key: mariadb-password
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
