apiVersion: v1
kind: Service
metadata:
  name: {{ include "veeamon-tour.mariadbHost" . }}
  labels:
    app: {{ include "veeamon-tour.mariadbHost" . }}
spec:
  clusterIP: None
  selector:
    app: {{ include "veeamon-tour.mariadbHost" . }}
  ports:
    - port: 3306
      targetPort: 3306
